spring:
  application:
    name: config-monitor-middleware
  mail:
    host: ny09nbcge.nbc.com 
    port: 25
    username: 502077553
    password: abcd

security:
  basic:
    enabled: false
management:
  security:
    enabled: false
     
refresh:
  endPoint: /refresh
  
cf:
  apiHost: api.labsysash.inbcu.com
  username: 206426113
  password: P@55word
  organization: POC
  space: develop,SRA-Linear-Programmatic;qa,SRA-Linear-Programmatic;
  
mail:
  to: Mohammed.AmmarM@nbcuni.com
  from: Mohammed.AmmarM@nbcuni.com
  subject: Unable to refresh the config file changes 
 

 
 