spring:
  application:
    name: config-monitor-middleware

security:
  basic:
    enabled: false
management:
  security:
    enabled: false
    
    
refresh:
  endPoint: /refresh
  
cf:
  apiHost: api.labsysash.inbcu.com
  username: 206426113
  password: P@55word
  organization: POC
  space: SRA-Linear-Programmatic